language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - cd client
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: reginaldo_game_app.surge.sh
  project: ./build/
on:
  branch: master