language: node_js
node_js:
  - "stable"
install: false
cache:
  directories:
    - node_modules
env:
  - TEST_DIR=client
script:
  - cd $TEST_DIR && npm install && npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: reginaldo_game_app.surge.sh
  project: ./build/
on:
  branch: master